config/routes.rb
        post "payable_account","revenue_report","cost_price","analysis_price","create_assets","manage_assets","show_asset"
        post "update_asset","other_fee","load_prod","return_order"
        get "cost_price","analysis_price","manage_assets","other_fee","complete_account","return_order","print_report"
        delete "destroy"
      end
    end
    resources :data_manages do
      collection do
        post "ajax_prod_serv"
      end
    end
    resources :market_manages do
      collection do
        get "makets_totals","makets_list","makets_reports","makets_views","makets_goal",
          "sale_orders","sale_order_list","stored_card_record","daily_consumption_receipt",
          "stored_card_bill", "daily_consumption_receipt_blank", "stored_card_bill_blank","gross_profit"
        post "search_month","search_report","search_sale_order","search_gross_profit"
        get "load_service","load_product","load_pcard","load_goal","load_over"
      end
    end
    resources :complaints do
      collection do
        post "consumer_search"
        get "consumer_list", "con_list", "meta_analysis","cost_price","satisfy_degree"
      end
      member do
        get "complaint_detail"
      end
    end
    resources :stations do
      collection do
        get "show_detail","show_video","see_video","search_video", "simple_station","set_tech"
        post "search","collect_info"
      end
    end
    resources :sales do
      collection do
        post "load_types",:delete_sale,:public_sale
      end
      member do
        post "update_sale"
      end
    end
    resources :package_cards do
      collection do
        post "pcard_types","add_pcard","search","delete_pcard"
        get "sale_records","search_list"
      end
      member do
        post "edit_pcard","update_pcard","request_material"
      end
    end
    resources :products do
      collection do
        post "edit_prod","add_prod","add_serv","serv_create","load_material","update_status","add_package","pack_create","destroy_prod"
        get "prod_services","package_service"
      end
      member do
        post "edit_prod","update_prod","serv_update","edit_serv","show_prod","show_serv","serve_delete","prod_delete","commonly_used",
          "edit_pack","pack_update"
      end
    end
    resources :materials do
      collection do
        get "out","search","order","page_materials","search_head_orders","search_supplier_orders","alipay",
          "print","cuihuo","cancel_order","page_outs","page_ins","page_back_records","page_head_orders","page_supplier_orders",
          "search_supplier_orders","pay_order","update_notices","material_order_pay","set_ignore","print_out",
          "cancel_ignore","search_materials","page_materials_losses","set_material_low_count_commit","print_code",
          "mat_loss_delete","mat_loss","back_good","back_good_search","back_good_commit", "reflesh_low_materials","print_mat"
        post "out_order","material_order","add","alipay_complete","mat_in","batch_check","set_material_low_commit","output_barcode",
          "mat_loss_add","modify_code","check_nums"
      end
      member do
        get "mat_order_detail","get_remark" ,"receive_order","tuihuo","set_material_low_count"
        post "remark"
      end
    end

    resources :staffs do
      collection do
        post "search"
      end
      member do
        post "load_work"
      end
    end
    resources :work_records
    resources :violation_rewards do
      collection do
        post "operate_voilate"
      end
    end
    resources :trains
    resources :month_scores do
      collection do
        get "update_sys_score"
      end
    end
    resources :salaries
    resources :current_month_salaries
    resources :material_order_manages do
      collection do
        get "flow_analysis", "storage_analysis"
      end
    end
    resources :staff_manages do
      collection do
        get "get_year_staff_hart"
        get "average_score_hart"
        get "average_cost_detail_summary"
      end
    end

    resources :suppliers do
      member do
        post "change"
      end
      collection do
        get "page_suppliers"
        post "check"
      end
    end
    resources :welcomes do
      collection do
        post "edit_store_name", "update_staff_password"
        post "info_detail"
      end
    end
    resources :customers do
      collection do
        post  "customer_mark", "single_send_message", "add_car"
        get "search", "add_car_get_datas","select_order"
      end
      member do
        get "order_prods", "revisits", "complaints", "sav_card_records", "pc_card_records"
      end
    end
    resources :revisits do
      collection do
        post "search", "process_complaint","send_mess"
        get "search_list"
      end
    end
    resources :messages do
      collection do
        post "search","set_message","alipay_compete"
        get "search_list","send_list","send_detailed","send_alipay","alipay_charge"
      end
      member do
        get "load_message"
      end
    end

    resources :roles do
      collection do
        get "staff"
        post "set_role","reset_role"
      end
    end

    resources :set_functions do
      collection do
        get "market_new", "market_new_commit", "market_edit", "market_edit_commit", "storage_new", "storage_new_commit",
          "storage_edit", "storage_edit_commit", "depart_new", "depart_new_commit", "sibling_depart_new",
          "sibling_depart_new_commit","depart_edit", "depart_edit_commit", "depart_del", "position_new",
          "position_new_commit", "position_edit_commit", "position_del_commit"
      end
    end

    resources :set_stores do
      collection do
        get "select_cities","cash_register","complete_pay","print_paper","single_print","plus_items","three_line_print"
        post "load_order","pay_order","edit_svcard","search_item","search_info","submit_item","edit_deduct"
        post "post_deduct","search_num"
      end
    end
    resources :station_datas do
      collection do
        post "create"
      end
    end
    resources :discount_cards do
      collection do
        get  "add_products_search", "edit", "edit_dcard_add_products", "edit_add_products_search"
        post "del_all_dcards"
      end
    end
    resources :save_cards do
      collection do
        post "del_all_scards"
      end
    end
    resources :materials_in_outs

    resources :work_orders do
      collection do
        get "work_orders_status"
      end
    end
  end

  match 'stores/:store_id/manage_content' => 'logins#manage_content'
  match 'stores/:store_id/materials_in' => 'materials_in_outs#materials_in'
  match 'stores/:store_id/materials_out' => 'materials_in_outs#materials_out'
  match 'get_material' => 'materials_in_outs#get_material'
  match 'stores/:store_id/create_materials_in' => 'materials_in_outs#create_materials_in'
  match 'create_materials_out' => 'materials_in_outs#create_materials_out'
  match 'save_cookies' => 'materials_in_outs#save_cookies'
  match 'stores/:store_id/materials/:mo_id/get_mo_remark' => 'materials#get_mo_remark'
  match 'stores/:store_id/materials/:mo_id/order_remark' => 'materials#order_remark'
  match 'stores/:store_id/uniq_mat_code' => 'materials#uniq_mat_code'
  match '/upload_code_matin' => 'materials_in_outs#upload_code_matin'
  match '/upload_code_matout' => 'materials_in_outs#upload_code_matout'
  match '/upload_checknum' => 'materials#upload_checknum'
  match 'stores/:store_id/materials_losses/add' => 'materials_losses#add'
  match 'stores/:store_id/materials_losses/delete' => 'materials_losses#delete'
  match 'stores/:store_id/materials_losses/view' => 'materials_losses#view'
  match 'materials/search_by_code' => 'materials#search_by_code'

  match 'stores/:store_id/depots' => 'depots#index'
  match 'stores/:store_id/check_mat_num' => 'materials#check_mat_num'
  resources :customers do
    collection do
      post "get_car_brands", "get_car_models", "check_car_num", "check_e_car_num","return_order","operate_order"
      get "show_revisit_detail","print_orders"
    end
    member do
      post "edit_car_num"
      get "delete_car_num"
      
    end
  end

  resources :orders do
    member do
      get "order_info", "order_staff"
    end
  end

  resources :materials do
    member do
      get "check"
    end
    collection do
      get "get_act_count", "out"
    end
  end
  
  resources :work_orders do
    collection do
      post "login"
    end
  end

  namespace :api do
    resources :orders do
      collection do
        post "login","add","pay","complaint","search_car","send_code","index_list","brands_products","finish",
          "confirm_reservation","refresh","pay_order","checkin", "show_car", "sync_orders_and_customer","get_user_svcard",
          "use_svcard","work_order_finished","login_and_return_construction_order","check_num","out_materials",
          "get_construction_order","search_by_car_num2","materials_verification","get_lastest_materails","stop_construction",
          "search_material"
      end
    end
    resources :syncs_datas do
      collection do
        post :syncs_db_to_all, :syncs_pics
      end
      member do
        get :return_sync_all_to_db
      end
    end
    resources :logins do
      collection do
        post :check_staff,:staff_login,:staff_checkin,:upload_img,:recgnite_pic
        get :download_staff_infos
      end
    end
    resources :licenses_plates do
      collection do
        post :upload_file
        get :send_file
      end
    end

    resources :new_app_orders do
      collection do
        post :customer_pcards, :package_make_order, :pcard_make_order_commit, :pcard_order_info

app/models/staff.rb
#encoding: utf-8
require 'fileutils'
class Staff < ActiveRecord::Base
  has_many :staff_role_relations, :dependent=>:destroy
  has_many :roles, :through => :staff_role_relations, :foreign_key => "role_id"
  has_many :salary_details
  has_many :work_records
  has_many :salaries
  has_many :station_staff_relations
  has_many :stations, :through => :station_staff_relations
  has_many :train_staff_relations
  has_many :violation_rewards
  has_many :staff_gr_records
  has_many :month_scores
  has_many :material_losses
  belongs_to :store
  has_many  :tech_orders

  
  validates :phone, :uniqueness => { :message => "联系方式已经存在!", :scope => :status}, :if => :staff_not_deleted?
  validates :username, :uniqueness => { :message => "用户名已经存在!", :scope => :status}, :if => :staff_not_deleted?
  #门店员工职务
  S_COMPANY = {:BOSS=>0,:CHIC=>2,:FRONT =>3,:TECHNICIAN =>1,:OTHER=>4} #0 老板 2 店长 3接待 1 技师 4其他
  N_COMPANY = {1=>"技师",3=>"接待",2=>"店长",4=>"其他"}
  LEVELS = {0=>"高级",1=>"中级",2=>"初级"}  #技师等级
  #总部员工职务
  STAFF_MENUS_AND_ROLES = {           #创建门店时创建的管理员将获取前台的所有权限
    :customers => 32767,
    :materials => 8589934591,
    :staffs => 131071,
    :datas => 4194303,
    :stations => 3,
    :sales => 4194303,
    :base_datas =>32767,
    :pay_cash => 1,
    :finances => 1
  }

  STATUS = {:normal => 0, :afl => 1, :vacation => 2, :resigned => 3, :deleted => 4}
  VALID_STATUS = [STATUS[:normal], STATUS[:afl], STATUS[:vacation]]
  STATUS_NAME = {0 => "在职", 1 => "请假", 2 => "休假", 3 => "离职", 4 => "删除"}
  scope :normal, where(:status => STATUS[:normal])
  scope :valid, where(:status => VALID_STATUS)
  scope :tech_job,where(:type_of_w => S_COMPANY[:TECHNICIAN])
  scope :not_deleted, where("status != #{STATUS[:deleted]}")
  scope :this_store,lambda{|store_id|where(:store_id => store_id)}

  S_HEAD = {:BOSS=>0,:MANAGER =>2,:NORMAL=>1} #0老板 2 店长 1员工
  N_HEAD = {1=>"员工",0=>"老板", 2=>"店长"}
  WORKING_STATS = {:FORMAL => 1, :PROBATION => 0}   #在职状态 0试用 1正式
  S_WORKING_STATS = {1 => "正式", 0 => "实习"}
  IS_DEDUCT = {:YES => 1, :NO =>0} #是否参加提成，1是 0否
  S_IS_DEDUCT = {1 => "是", 0 => "否"}
  #教育程度
  N_EDUCATION = {0 => "研究生", 1 => "本科", 2 => "专科", 3 => "高中", 4 => "初中",
    5 => "小学", 6 => "无"}
  S_EDUCATION = {:GRADUATE => 0,  :UNIVERSITY => 1, :COLLEGE => 2, :SENIOR => 3, :JUNIOR => 4, :PRIMARY => 5, :NONE => 6}


  #分页页数
  PerPage = 20

  def staff_not_deleted?
    status != STATUS[:deleted]
  end

  attr_accessor :password
  #validates :password, :allow_nil => true, :length=>{:within=>6..20} #:confirmation=>true

  after_update :insert_staff_gr_record

  def insert_staff_gr_record
    if (self.level_changed? || self.base_salary_changed? || self.deduct_at_changed? || self.deduct_end_changed? || 
          self.deduct_percent_changed? || self.working_stats_changed? || self.secure_fee_changed? || self.reward_fee_changed?)
      StaffGrRecord.create(:staff_id => self.id, :base_salary => self.base_salary,:deduct_at => self.deduct_at,
        :deduct_end => self.deduct_end,:deduct_percent => self.deduct_percent, :working_stats => self.working_stats,
        :level => self.level)
    end
  end

  def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

  def encrypt_password
    self.encrypted_password=encrypt(password)
  end

  def operate_picture(photo,original_filename, status)
    store_id = self.store.id
    FileUtils.remove_dir "#{File.expand_path(Rails.root)}/public/uploads/#{store_id}/#{self.id}" if status.eql?("update") && FileTest.directory?("#{File.expand_path(Rails.root)}/public/uploads/#{store_id}/#{self.id}")
    FileUtils.mkdir_p "#{File.expand_path(Rails.root)}/public/uploads/#{store_id}/#{self.id}"
    File.new(Rails.root.join('public', "uploads", "#{store_id}", "#{self.id}", original_filename), 'a+')
    File.open(Rails.root.join('public', "uploads", "#{store_id}", "#{self.id}", original_filename), 'wb') do |file|
      file.write(photo.read)
    end
    file_path = "#{File.expand_path(Rails.root)}/public/uploads/#{store_id}/#{self.id}/#{original_filename}"
    img = MiniMagick::Image.open file_path,"rb"

    Constant::STAFF_PICSIZE.each do |size|
      resize = size > img["width"] ? img["width"] : size
      new_file = file_path.split(".")[0]+"_#{resize}."+file_path.split(".").reverse[0]
      resize_file_name = original_filename.split(".")[0]+"_#{resize}."+original_filename.split(".").reverse[0]
      self.update_attribute(:photo, "/uploads/#{store_id}/#{self.id}/#{resize_file_name}")
      img.run_command("convert #{file_path}  -resize #{resize}x#{resize} #{new_file}")
    end
  end

  def self.update_staff_working_stats
    Staff.where("working_stats = 0").each do |staff|
      diff_day = (Time.now - staff.created_at).to_i / (24 * 60 * 60)
      if diff_day >= (staff.probation_days||=0)
        staff.update_attribute(:working_stats, 1)
      end
    end
  end

  private
  def encrypt(string)
    self.salt = make_salt if new_record?
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.new.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

  def self.search_work_record_sql
    "current_day,
      SUM(attendance_num) as attendance_num_sum,
      SUM(construct_num) as construct_num_sum,
      SUM(materials_used_num) as materials_used_num_sum,
      SUM(materials_consume_num) as materials_consume_num_sum,
      SUM(water_num) as water_num_sum,
      SUM(complaint_num) as complaint_num_sum,
      SUM(train_num) as train_num_sum,
      SUM(reward_num) as reward_num_sum,
      SUM(violation_num) as violation_num_sum,
      SUM(gas_num) as gas_num_sum"
  end

end

app/helpers/staffs_helper.rb
#encoding: utf-8
module StaffsHelper
  
  def current_month_access_result(month_score)
    total = 100- (month_score.nil? ? 0 : month_score.sys_score.to_i)
    if total >= 90
      access_result = "优秀"
    end
    if total >= 80 && total < 90
      access_result = "良好"
    end
    if total >= 70 && total < 80
      access_result = "一般"
    end
    if total >= 60 && total < 70
      access_result = "及格"
    end
    if total < 60
      access_result = "不及格"
    end
    access_result
  end

  def get_month_score_obj(staff)
    staff.month_scores.where("current_month = #{DateTime.now.months_ago(1).strftime("%Y%m")}").first
  end

  def get_train_status(train_id, staff_id)
    train_staff_relation = TrainStaffRelation.where("train_id = #{train_id} and staff_id = #{staff_id}").first
    train_staff_relation.status
  end

end

app/views/staffs/_edit.html.erb
<div class="tab_popup" style="display:none;" id="edit_staff_area">
  <div class="popup_box">
    <h1>编辑员工<a href="javascript:void(0)" class="close">关闭</a></h1>
    <%= form_for(@staff, :url => store_staff_path(@store, @staff), :html => {:method => :put, :multipart => true, "data-type" => 'script'}, :remote => true) do |f| %>
      <div class="popup_body">
        <div class="popup_body_area">
          <div class="item">
            <label><span class="red">*</span>姓名：</label>
            <%= f.text_field :name %>
          </div>
          <div class="item">
            <label>性别：</label>
            <%= f.radio_button :sex, Constant::SEX[:MALE], :checked => f.object.sex ?  true : false %> 男&nbsp;&nbsp;
            <%= f.radio_button :sex, Constant::SEX[:FEMALE], :checked => f.object.sex ? false : true %> 女
          </div>
          <div class="item">
            <label>部门：</label>
            <select name="staff[position]" id="staff_position" onchange="load_work();">
              <%@departs[Department::TYPES[:DEPARTMENT]].each do |pos|%>
                <option value="<%= pos[0] %>"<% if f.object.position==pos[0] %>selected<%end%>><%= pos[1].name %></option>
              <%end if @departs[Department::TYPES[:DEPARTMENT]]%>
            </select>
          </div>
          <div class="item">
            <label>职务：</label>
            <select name="staff[department_id]" id="staff_department_id">
              <option value="" style="display:none">请选择</option>
              <%@departs[Department::TYPES[:POSITION]].each do |pos|%>
                <option value="<%= pos[0] %>" id="<%=pos[1].dpt_id%>"
                        <% if f.object.position != pos[1].dpt_id %>style="display:none"<%elsif f.object.department_id==pos[0] %>selected<%end%>><%= pos[1].name %></option>
                      <%end if @departs[Department::TYPES[:POSITION]]%>
            </select>
          </div>
          <div class="item">
            <label>类别：</label>
            <%= f.select :type_of_w, Staff::N_COMPANY.invert %>
          </div>
          <div class="item">
            <label>教育程度：</label>
            <%= f.select :education, Staff::N_EDUCATION.invert %>
          </div>
          <div class="item">
            <label>等级：</label>
            <%= f.select :level, Staff::LEVELS.invert %>
          </div>
          <div class="item">
            <label>员工状态：</label>
            <%= f.select :working_stats, Staff::S_WORKING_STATS.invert %>
          </div>
          <div class="item">
            <label>实习时长(天):</label>
            <%= f.text_field :probation_days, :disabled => f.object.working_stats == 1 ? true : false %>
          </div>
          <div class="item">
            <label><span class="red" style="display:none">*</span>实习薪资：</label>
            <%= f.text_field :probation_salary, :disabled => f.object.working_stats == 1 ? true : false %>
          </div>
          <div class="item">
            <label><span class="red">*</span>正式薪资：</label>
            <%= f.text_field :base_salary %>
          </div>
          <div class="item">
            <label>出生年月：</label>
            <%= f.text_field :birthday, :class => "Wdate", :readonly => true, :onClick => "WdatePicker();",
              :value => f.object.birthday.nil? ? "" : f.object.birthday.strftime("%Y-%m-%d") %>
          </div>
          <div class="item">
            <label><span class="red">*</span>联系方式：</label>
            <%= f.text_field :phone %>
          </div>
          <div class="item">
            <label>籍贯：</label>
            <%= f.text_field :hometown %>
          </div>
          <div class="item">
            <label><span class="red">*</span>身份证号：</label>
            <%= f.text_field :id_card %>
          </div>
          <div class="item">
            <label>民族：</label>
            <%= f.text_field :nation %>
          </div>
          <div class="item">
            <label>政治面貌：</label>
            <%= f.text_field :political %>
          </div>
          <div class="item">
            <label><span class="red">*</span>地址：</label>
            <%= f.text_field :address %>
          </div>
          <div class="item">
            <label>是否提成：</label>
            <%= f.check_box :is_deduct, :value => 1, :checked => true %>
          </div>
          <div class="item">
            <label>社保扣款：</label>
            <%= f.text_field :secure_fee %>
          </div>
          <div class="item">
            <label>补贴金额：</label>
            <%= f.text_field :reward_fee %>
          </div>
          <div class="item">
            <label>按考核分发底薪：</label>
            <%= f.check_box :is_score_ge_salary, :value => 1 %>
          </div>
          <div class="item_textarea">
            <label>上传照片：</label><%= f.file_field :photo, :class => "file" %>
            <% if !f.object.photo.nil? %>
              <span class="show_pic"><%= image_tag "#{f.object.photo}" %>
              <% end %>
            </span>
          </div>
          <div class="item">
            <label>登录系统：</label>
            <input type="checkbox" name="is_access" value="1" <% unless @staff.encrypted_password.nil? %> checked<%end%> />
          </div>
        </div>
        <div class="btn_box">
          <button class="confirm_btn" id="edit_staff_btn" type="button">编辑</button></div>
        <div class="clear"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/staffs/_month_score_tab.html.erb
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="data_table myTable" id="month_score_table">
     <thead>
          <tr class="hbg">
            <th><span class="sort_u_s" onclick="sort_change(this)">时间</span></th>
            <th>系统打分</th>
            <th>店长打分</th>
            <th>当月评估结果</th>
          </tr>
      </thead>
      <tbody>
        <% @month_scores.each do |month_score| %>
          <tr>
            <td><%= month_score.current_month %></td>
            <td id="<%= (!@current_month_score.nil? && @current_month_score.current_month == month_score.current_month) ? "current_month_score" : "" %>"><%= month_score.sys_score %></td>
            <td id="<%= (!@current_month_score.nil? && @current_month_score.current_month == month_score.current_month) ? "current_month_manage_score" : "" %>"><%= month_score.manage_score.nil? ? "未打分" : month_score.manage_score %></td>
            <td><%= current_month_access_result(month_score) %></td>
          </tr>
        <% end %>
      </tbody>
</table>
<%= will_paginate @month_scores, :class => "pageTurn", :previous_label => "上一页",
    :next_label => "下一页" %>

app/views/staffs/_reward_tab.html.erb
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="data_table" id="reward_table">
  <thead>
    <tr class="hbg">
      <th><span class="sort_u_s" onclick="sort_change(this)">时间</span></th>
      <th width="25%">原因</th>
      <th>奖励方式</th>
      <th>处理状态</th>
      <th>奖励分值</th>
      <th>奖励金额</th>
      <th width="25%">理由</th>
    </tr>
  </thead>
  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= reward.situation %></td>
        <td><%= ViolationReward::N_REWARD[reward.process_types] %></td>
        <td>
          <% unless reward.status %>
            <% if permission?(:staffs, :deal_violation) %><%= link_to "处理", "javascript:void(0)", :class => "process_reward", :id => reward.id, :name => @store.id %><% end %>
          <% else %>
            已处理
          <% end %>
        </td>
        <td><%= reward.score_num %></td>
        <td><%= reward.salary_num %></td>
        <td><%= reward.mark %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @rewards, :class => "pageTurn", :previous_label => "上一页",
  :next_label => "下一页" %>

app/views/staffs/create.js.erb
<% if @flash_notice == "success" %>
  window.location.replace("<%= store_staffs_path(@store) %>");
<% else %>
  tishi_alert("<%= @flash_notice.html_safe() %>");
  $("#new_staff_btn").removeAttr("disabled");
<% end %>

app/views/staffs/edit.js.erb
$("#staff_edit").html('<%= escape_javascript(render :partial => '/staffs/edit') %>');
popup("#edit_staff_area");
$("#edit_staff_close, #edit_staff_cancel").bind('click',function(){
    $(".mask").hide();
    $("#edit_staff_area").html('');
    return false;
});

app/views/staffs/search.js.erb
$("#staff_info").html('<%= j(render :partial => "staff_list") %>')
$(".data_table > tbody > tr:odd").addClass("tbg");
$(".data_tab_table > tbody > tr:odd").addClass("tbg");

app/views/staffs/show.html.erb
<div class="main">
  <div class="box">
    <div class="data_box">
      <div class="way_menu"><%= link_to "员工一览", store_staffs_path(@store) %> &gt; 员工详情</div>
      <div class="data_body_title">
        <div class="data_body_p">
          <span>姓名：<%= @staff.name %></span>
          <span>部门：<%= @departs[@staff.position]%></span>
          <span>等级：<%= Staff::LEVELS[@staff.level] %></span>
          <span>职务：<%=@departs[@staff.department_id]%></span>
          <% if permission?(:staffs, :edit_show_staff) %>
          <a href="javascript:void(0)" id="staff_detail" onclick="show_staff(<%=@staff.id%>,<%=@staff.store_id%>)">详情</a><% end %></div>
      </div>
      <div class="clear"></div>
      <div class="tab_head">
        <ul>
          <li class="hover">绩效记录</li>
          <li>培训记录</li>
          <li>奖励记录</li>
          <li>违规记录</li>
          <li>工资记录</li>
        </ul>
      </div>
      <div class="data_body" id="ajax_paginate">
        <div>
          <div id="work_record_tab">
            <%= render :partial => "work_record_tab" %>
          </div>
        </div>


        <div style="display:none;" id="train_tab">
          <%= render :partial => "train_tab" %>
        </div>

        <div style="display:none;" id="reward_tab">
          <%= render :partial => "reward_tab" %>
        </div>

        <div style="display:none;" id="violation_tab">
          <%= render :partial => "violation_tab" %>
        </div>

        <div style="display:none;" id="salary_tab">
          <%= render :partial => "salary_tab" %>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="foot"><p>Copyright © 2013 杭州鼎洪 版权所有</p></div>
<div class="mask"></div>
<div class="maskOne"></div>

<div class="tab_popup" style="display:none;" id="manage_score_area">
  <% if @current_month_score.nil? %>
    <div class="popup_box">
      <h1>店长打分<a href="javascript:void(0)" class="close">关闭</a></h1>
      <div class="popup_body">
        <div class="popup_body_area">
          <div class="item">
            系统没有上一个月的绩效记录
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
  <% else %>
    <%= form_for(@current_month_score, :url => store_month_score_path(@store, @current_month_score), :html => {:method => :put, "data-type" => 'script'}, :remote => true) do |f| %>
      <div class="popup_box">
        <h1>店长打分<a href="javascript:void(0)" class="close">关闭</a></h1>
        <div class="popup_body">
          <div class="popup_body_area">
            <div class="item">
              <label>分数：</label>
              <%= f.text_field :manage_score %>
            </div>
            <div class="clear"></div>
            <div class="item_textarea">
              <label>理由：</label>
              <%= f.text_area :reason, :cols => "", :rows => "", :class => "width_textarea" %>
            </div>
            <input type="hidden" name="month_score[is_syss_update]" value="1"/>
            <input type="hidden" name="staff_id" value="<%= @staff.id %>"/>
            <div class="btn_box"><button class="confirm_btn" id="manage_score_btn_validate">确定</button><button class="cancel_btn">取消</button></div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div id="process"></div>
<div id="staff_edit"></div>

app/views/staffs/update.js.erb
<% if @flash_notice == "success" %>
  window.location.replace("<%= store_staff_path(@store, @staff) %>");
<% else %>
  tishi_alert("<%= @flash_notice.html_safe() %>");
  $("#edit_staff_btn").removeAttr("disabled");
<% end %>