config/routes.rb
LantanBAM::Application.routes.draw do

  resources :syncs do
    get "upload_file"
    collection do
      post "upload_image"
    end
  end

  resources :stations do
    collection do
      post "handle_order"
    end
  end
  resources :work_records do
    collection do
      post "adjust_types"
    end
  end
  resources :messages do
    collection do
      get "wechat_msg"
    end
  end
  resources :package_cards do
    collection do
      post "on_weixin"
    end
  end

  root :to => 'logins#index'
  resources :logins do
    collection do
      get "logout", "send_validate_code","phone_login","manage_content"
      post "forgot_password","login_phone"
    end
  end
  match "logout" => "logins#logout"
  match "phone_login" => "logins#phone_login"
  match "manage_content" => "logins#manage_content"
  resources :stores do

    resources :micro_stores do
      collection do
        get :upload_content
        post :create_know
      end
      member do
        post :edit_know
      end
    end

    resources :check_materials do
      collection do
        get :check_record,:submit_check,:file_list
        post :batch_check,:submit_check,:submit_xls
      end
    end
    resources :adverts do
    end
    resources :finance_reports do
      collection do
        get "fee_manage","revenue_report","fee_report","pay_account","payable_account","manage_account"
        post "fee_manage","show_fee","fee_report","load_account","pay_account","manage_account"
        post "payable_account","revenue_report","cost_price","analysis_price","create_assets","manage_assets","show_asset"
        post "update_asset","other_fee","load_prod","return_order"
        get "cost_price","analysis_price","manage_assets","other_fee","complete_account","return_order","print_report"
        delete "destroy"
      end
    end
    resources :data_manages do
      collection do
        post "ajax_prod_serv"
      end
    end
    resources :market_manages do
      collection do
        get "makets_totals","makets_list","makets_reports","makets_views","makets_goal",
          "sale_orders","sale_order_list","stored_card_record","daily_consumption_receipt",
          "stored_card_bill", "daily_consumption_receipt_blank", "stored_card_bill_blank","gross_profit"
        post "search_month","search_report","search_sale_order","search_gross_profit"
        get "load_service","load_product","load_pcard","load_goal","load_over"
      end
    end
    resources :complaints do
      collection do
        post "consumer_search"
        get "consumer_list", "con_list", "meta_analysis","cost_price","satisfy_degree"
      end
      member do
        get "complaint_detail"
      end
    end
    resources :stations do
      collection do
        get "show_detail","show_video","see_video","search_video", "simple_station","set_tech"
        post "search","collect_info"
      end
    end
    resources :sales do
      collection do
        post "load_types",:delete_sale,:public_sale
      end
      member do
        post "update_sale"
      end
    end
    resources :package_cards do
      collection do
        post "pcard_types","add_pcard","search","delete_pcard"
        get "sale_records","search_list"
      end
      member do
        post "edit_pcard","update_pcard","request_material"
      end
    end
    resources :products do
      collection do
        post "edit_prod","add_prod","add_serv","serv_create","load_material","update_status","add_package","pack_create","destroy_prod"
        get "prod_services","package_service"
      end
      member do
        post "edit_prod","update_prod","serv_update","edit_serv","show_prod","show_serv","serve_delete","prod_delete","commonly_used",
          "edit_pack","pack_update"
      end
    end
    resources :materials do
      collection do
        get "out","search","order","page_materials","search_head_orders","search_supplier_orders","alipay",
          "print","cuihuo","cancel_order","page_outs","page_ins","page_back_records","page_head_orders","page_supplier_orders",
          "search_supplier_orders","pay_order","update_notices","material_order_pay","set_ignore","print_out",
          "cancel_ignore","search_materials","page_materials_losses","set_material_low_count_commit","print_code",
          "mat_loss_delete","mat_loss","back_good","back_good_search","back_good_commit", "reflesh_low_materials","print_mat"
        post "out_order","material_order","add","alipay_complete","mat_in","batch_check","set_material_low_commit","output_barcode",
          "mat_loss_add","modify_code","check_nums"
      end
      member do
        get "mat_order_detail","get_remark" ,"receive_order","tuihuo","set_material_low_count"
        post "remark"
      end
    end

    resources :staffs do
      collection do
        post "search"
      end
      member do
        post "load_work"
      end
    end
    resources :work_records
    resources :violation_rewards do
      collection do
        post "operate_voilate"
      end
    end
    resources :trains
    resources :month_scores do
      collection do
        get "update_sys_score"
      end
    end
    resources :salaries
    resources :current_month_salaries
    resources :material_order_manages do
      collection do
        get "flow_analysis", "storage_analysis"
      end
    end
    resources :staff_manages do
      collection do
        get "get_year_staff_hart"
        get "average_score_hart"
        get "average_cost_detail_summary"
      end
    end

    resources :suppliers do
      member do
        post "change"
      end
      collection do
        get "page_suppliers"
        post "check"
      end
    end
    resources :welcomes do
      collection do
        post "edit_store_name", "update_staff_password"
        post "info_detail"
      end
    end
    resources :customers do
      collection do
        post  "customer_mark", "single_send_message", "add_car"
        get "search", "add_car_get_datas","select_order"
      end
      member do
        get "order_prods", "revisits", "complaints", "sav_card_records", "pc_card_records"
      end
    end
    resources :revisits do
      collection do
        post "search", "process_complaint","send_mess"
        get "search_list"
      end
    end
    resources :messages do
      collection do
        post "search","set_message","alipay_compete"
        get "search_list","send_list","send_detailed","send_alipay","alipay_charge"
      end
      member do
        get "load_message"
      end
    end

    resources :roles do
      collection do
        get "staff"
        post "set_role","reset_role"
      end
    end

    resources :set_functions do
      collection do
        get "market_new", "market_new_commit", "market_edit", "market_edit_commit", "storage_new", "storage_new_commit",
          "storage_edit", "storage_edit_commit", "depart_new", "depart_new_commit", "sibling_depart_new",
          "sibling_depart_new_commit","depart_edit", "depart_edit_commit", "depart_del", "position_new",
          "position_new_commit", "position_edit_commit", "position_del_commit"
      end
    end

    resources :set_stores do
      collection do
        get "select_cities","cash_register","complete_pay","print_paper","single_print","plus_items","three_line_print"
        post "load_order","pay_order","edit_svcard","search_item","search_info","submit_item","edit_deduct"
        post "post_deduct","search_num"
      end
    end
    resources :station_datas do
      collection do
        post "create"
      end
    end
    resources :discount_cards do
      collection do
        get  "add_products_search", "edit", "edit_dcard_add_products", "edit_add_products_search"
        post "del_all_dcards"
      end
    end
    resources :save_cards do
      collection do
        post "del_all_scards"
      end
    end
    resources :materials_in_outs

    resources :work_orders do
      collection do
        get "work_orders_status"
      end
    end
  end

  match 'stores/:store_id/manage_content' => 'logins#manage_content'
  match 'stores/:store_id/materials_in' => 'materials_in_outs#materials_in'
  match 'stores/:store_id/materials_out' => 'materials_in_outs#materials_out'
  match 'get_material' => 'materials_in_outs#get_material'
  match 'stores/:store_id/create_materials_in' => 'materials_in_outs#create_materials_in'
  match 'create_materials_out' => 'materials_in_outs#create_materials_out'
  match 'save_cookies' => 'materials_in_outs#save_cookies'
  match 'stores/:store_id/materials/:mo_id/get_mo_remark' => 'materials#get_mo_remark'
  match 'stores/:store_id/materials/:mo_id/order_remark' => 'materials#order_remark'
  match 'stores/:store_id/uniq_mat_code' => 'materials#uniq_mat_code'
  match '/upload_code_matin' => 'materials_in_outs#upload_code_matin'
  match '/upload_code_matout' => 'materials_in_outs#upload_code_matout'
  match '/upload_checknum' => 'materials#upload_checknum'
  match 'stores/:store_id/materials_losses/add' => 'materials_losses#add'
  match 'stores/:store_id/materials_losses/delete' => 'materials_losses#delete'
  match 'stores/:store_id/materials_losses/view' => 'materials_losses#view'
  match 'materials/search_by_code' => 'materials#search_by_code'

  match 'stores/:store_id/depots' => 'depots#index'
  match 'stores/:store_id/check_mat_num' => 'materials#check_mat_num'
  resources :customers do
    collection do
      post "get_car_brands", "get_car_models", "check_car_num", "check_e_car_num","return_order","operate_order"
      get "show_revisit_detail","print_orders"
    end
    member do
      post "edit_car_num"
      get "delete_car_num"
      
    end
  end

  resources :orders do
    member do

app/models/sale.rb
#encoding: utf-8
class Sale < ActiveRecord::Base
  has_many :sale_prod_relations
  has_many :products, :through => :sale_prod_relations do
    def service
      where("is_service = true")
    end
  end

  belongs_to :store
  STATUS={:UN_RELEASE =>0,:RELEASE =>1,:DESTROY =>2} #0 未发布 1 发布 2 删除
  STATUS_NAME={0=>"未发布",1=>"已发布",2=>"已删除"}
  DISC_TYPES = {:FEE =>1,:DIS =>0} #1 优惠金额  0 优惠折扣
  DISC_TYPES_NAME = {1 => "金额优惠", 0 => "折扣"}
  DISC_TIME = {:DAY =>1,:MONTH =>2,:YEAR =>3,:WEEK =>4,:TIME =>0} #1 每日 2 每月 3 每年 4 每周 0 时间段
  DISC_TIME_NAME ={1=>"本年度每天",2=>"本年度每月",3=>"本年度每年",4=>"本年度每周" }
  SUBSIDY = { :NO=>0,:YES=>1} # 0 不补贴 1 补贴
  TOTAL_DISC = [DISC_TIME[:DAY],DISC_TIME[:MONTH],DISC_TIME[:YEAR],DISC_TIME[:WEEK]]
  scope :valid, where("((ended_at > '#{Time.now}' and disc_time_types = #{DISC_TIME[:TIME]}) or disc_time_types!= #{DISC_TIME[:TIME]}) and is_subsidy = true and status=#{STATUS[:RELEASE]}")
  require 'mini_magick'

  #生成code
  def self.set_code(length,model_n,code_name)
    chars = (1..9).to_a + ("a".."z").to_a + ("A".."Z").to_a
    code=(1..length).inject(Array.new) {|codes| codes << chars[rand(chars.length)]}.join("")
    codes=eval(model_n.capitalize).all.map(&:"#{code_name}")
    if codes.index(code) 
      set_code(length,model_n,code_name)
    else
      return code
    end
  end

  #上传图片并缩放不同比例 目前为50,100,200和原图
  #img_url 上传文件的路径 sale_id所属对象的id
  #pic_types存放文件的文件夹名称 store_id 门店编号
  def self.upload_img(img_url,object,pics_size,img_code=nil)
    path = Constant::LOCAL_DIR
    begin
      store_id = object.store_id
    rescue
      store_id = object.id
    end
    dirs = ["","#{pics_size.delete_at(-1)}","#{store_id}","#{object.id}",""]
    dirs.each_with_index {|dir,index| Dir.mkdir path+dirs[0..index].join("/")   unless File.directory? path+dirs[0..index].join("/") }
    file = img_url.original_filename
    filename = "#{dirs.join("/")}#{img_code}img#{object.id}."+ file.split(".").reverse[0]
    File.open(path+filename, "wb")  {|f|  f.write(img_url.read) }
    img = MiniMagick::Image.open path+filename,"rb"
    pics_size.each do |size|
      new_file="#{dirs.join('/')}#{img_code}img#{object.id}_#{size}."+ file.split(".").reverse[0]
      resize = size > img["width"] ? img["width"] : size
      height = img["height"].to_f/img["width"].to_f > 5.0/6 ?  250 : resize
      img.run_command("convert #{path+filename}  -resize #{resize}x#{height} #{path+new_file}")
    end
    return filename
  end
  

  #统计活动订单的数量，金额，及优惠金额
  def self.count_sale_orders_search(store_id,started_at=nil,ended_at=nil,name=nil)
    sql ="select count(o.id) o_num,concat_ws('--',date_format(s.started_at,'%Y.%m.%d'),date_format(s.ended_at,'%Y.%m.%d')) day,
         s.description intro,s.name,s.id,s.disc_time_types from sales s  inner join orders o on s.id=o.sale_id where s.store_id=#{store_id}"
    sql += " and date_format(o.created_at,'%Y-%m-%d')>='#{started_at}'" unless started_at.nil? || started_at =="" || started_at.length==0
    sql += " and date_format(o.created_at,'%Y-%m-%d')<='#{ended_at}'" unless ended_at.nil? || ended_at =="" || ended_at.length==0
    sql += " and s.name like '#{name}'"   unless name.nil? || name =="" || name.length==0
    sql += " group by s.id"
    return Sale.find_by_sql(sql)
  end
end

app/controllers/station_datas_controller.rb
#encoding: utf-8
class StationDatasController < ApplicationController
  layout "station"
  before_filter :sign?
  before_filter :find_store

  def index
    @stations = @store.stations.valid.paginate(:page => params[:page] ||= 1, :per_page => Station::PerPage)
  end

  def new
    @categories = Category.where(["types = ? and store_id = ? ", Category::TYPES[:service], @store.id]).inject({}){|hash,c|hash[c.id]=c.name;hash};
    @services = @categories.empty? ? {} : Product.is_normal.where(:category_id => @categories.keys).group_by { |p| p.category_id }
    pack_serv = Product.is_normal.where(:category_id => Product::PACK[:PACK],:store_id=>@store.id)
    need_product = Product.joins(:category).is_normal.where(:is_service => Product::PROD_TYPES[:PRODUCT],:is_added=>Product::IS_ADDED[:YES],:store_id=>@store.id)
    unless pack_serv.blank?
      @categories.merge!(Product::PACK_SERVIE)
      @services.merge!(Product::PACK[:PACK]=>pack_serv)
    end
    unless need_product.blank?
      @categories.merge!(Product::NEED_WORK)
      @services.merge!(Product::WORK[:WORK]=>need_product)
    end
    respond_to do |format|
      format.js
    end
  end

  def create
    name = params[:station_name].strip
    code = params[:station_code].strip
    products = params[:product_ids]
    station_services = []
    s = Station.where(["code = ? and store_id = ? and status != ?", code, @store.id, Station::STAT[:DELETED]])
    if s.blank?
      station = Station.new(:name => name, :code => code, :store_id => @store.id, :status =>params[:status])
      if station.save
        products.each do |p|
          station_services << StationServiceRelation.new(:station_id => station.id, :product_id => p.to_i)
        end
        StationServiceRelation.import station_services
        @status = 1
      else
        @status = 0
      end
    else
      @status = 2
    end
  end

  def edit
    @station = Station.find_by_id(params[:id].to_i)
    @has_services = @station.products.map(&:id)
    @categories = Category.where(["types = ? and store_id = ? ", Category::TYPES[:service], @store.id]).inject({}){|hash,c|hash[c.id]=c.name;hash};
    @services = @categories.empty? ? {}:Product.is_normal.where(:category_id => @categories.keys).group_by { |p| p.category_id }
    pack_serv = Product.is_normal.where(:category_id => Product::PACK[:PACK],:store_id=>@store.id)
    need_product = Product.joins(:category).is_normal.where(:is_service => Product::PROD_TYPES[:PRODUCT],:is_added=>Product::IS_ADDED[:YES],:store_id=>@store.id)
    unless pack_serv.blank?
      @categories.merge!(Product::PACK_SERVIE)
      @services.merge!(Product::PACK[:PACK]=>pack_serv)
    end
    unless need_product.blank?
      @categories.merge!(Product::NEED_WORK)
      @services.merge!(Product::WORK[:WORK]=>need_product)
    end
    respond_to do |format|
      format.js
    end
  end

  def update
    name = params[:edit_station_name].strip
    code = params[:edit_station_code].strip
    products = params[:edit_product_ids]
    id = params[:id].to_i
    station_services = []
    s = Station.where(["id != ? and code = ? and store_id = ? and status != ?", id, code, @store.id, Station::STAT[:DELETED]])
    if s.blank?
      station = Station.find_by_id(id)
      if station.update_attributes(:name => name, :code => code, :store_id => @store.id,:status => params[:edit_status])
        StationServiceRelation.delete_all(:station_id => id)
        products.each do |p|
          station_services << StationServiceRelation.new(:station_id => station.id, :product_id => p.to_i)
        end
        StationServiceRelation.import station_services
        @status = 1
      else
        @status = 0
      end
    else
      @status = 2
    end
  end

  def destroy
    station = Station.find_by_id(params[:id])
    if station.update_column(:status, Station::STAT[:DELETED])
      @status = 1
    else
      @status = 0
    end
  end

  private

  def find_store
    @store = Store.find_by_id(params[:store_id]) || not_found
  end
end

app/views/station_datas/_edit.html.erb
<div class="popup_box">
  <h1>编辑工位<a href="javascript:void(0)" class="close">关闭</a></h1>
  <div class="popup_body">
    <%= form_tag "/stores/#{@store.id}/station_datas/#{@station.id}", :method => :put, :remote => true, "data-type" => 'script', :class=>"station_form" do %>
      <div class="popup_body_area">
        <div class="item station_name">
          <label><span class="red">*</span>名称：</label>
          <input type="text" size="30" id="edit_station_name" name="edit_station_name" value="<%= @station.name %>"/>
        </div>
        <div class="item">
          <label><span class="red">*</span>编号：</label>
          <input type="text" size="30" id="edit_station_code" name="edit_station_code" value="<%= @station.code %>"/>
        </div>
        <div class="item">
          <label><span class="red">*</span>状态：</label>
          <select name="edit_status">
            <%Station::STAT_NAME.each do |k,v|%>
              <option value="<%= k %>" <%if k == @station.status %>selected<%end%>><%= v %></option>
            <%end%>
          </select>
        </div>
        <div class="item_textarea" style="width:605px;">
          <label><span class='red'>*</span>服务：</label>
          <div class="item_rbox">
            <% @services.each do |k,v| %>
              <div class="serv_ul">
                <h1 style="padding-left:5px;"><input type="checkbox" onclick="$(this).parent().parent().find('#<%=k%> input').attr('checked',this.checked);" /><%=@categories[k] %></h1>
                <%v.each do |p|%>
                  <span id="<%=k%>"><input type="checkbox" name="edit_product_ids[]" value="<%= p.id %>"
                                           <% if @has_services.include?(p.id) %>checked<% end %> /><%= p.name %></span>&nbsp;&nbsp;
                  <%end%>
              </div>
            <% end unless @services.blank? %>

          </div>
        </div>
      </div>
      <div class="btn_box">
        <button type="button" class="confirm_btn" onclick="edit_station_valid(this)">确定</button>
      </div>
    <% end %>
  </div>
</div>

app/views/station_datas/_new.html.erb
<div class="popup_box">
  <h1>新建工位<a href="javascript:void(0)" class="close">关闭</a></h1>
  <div class="popup_body">
    <%= form_tag "/stores/#{@store.id}/station_datas", :method => :post, :remote => true, "data-type" => 'script', :class=>"station_form" do %>
      <div class="popup_body_area">
        <div class="item station_name">
          <label><span class="red">*</span>名称：</label>
          <input type="text" size="30" id="station_name" name="station_name"/>
        </div>
        <div class="item">
          <label><span class="red">*</span>编号：</label>
          <input type="text" size="30" id="station_code" name="station_code"/>
        </div>
        <div class="item">
          <label><span class="red">*</span>状态：</label>
          <select name="status">
            <%Station::STAT_NAME.each do |k,v|%>
              <option value="<%= k %>" <%if k == Station::STAT[:NORMAL]%>selected<%end%>><%= v %></option>
            <%end%>
          </select>
        </div>
        <div class="item_textarea" style="width:605px;">
          <label><span class='red'>*</span>服务：</label>
          <div class="item_rbox">
            <% @services.each do |k,v| %>
              <div class="serv_ul">
                <h1 style="padding-left:5px;"><input type="checkbox" onclick="$(this).parent().parent().find('#<%=k%> input').attr('checked',this.checked);" /><%=  @categories[k] %></h1>
                <%v.each do |p|%>
                  <span id="<%=k%>"><input type="checkbox" name="product_ids[]" value="<%= p.id %>"/><%= p.name %></span>&nbsp;&nbsp;
                <%end%>
              </div>
            <% end unless @services.blank?  %>
          </div>
        </div>
      </div>
      <div class="btn_box">
        <button type="button" class="confirm_btn" onclick="new_station_valid(this)">确定</button>
      </div>
    <% end %>
  </div>
</div>

app/views/station_datas/create.js.erb
<% if @status==2 %>
tishi_alert("新建失败，已有同编号的工控机!");
<% elsif @status==0 %>
tishi_alert("新建失败!");
<% else %>
window.location.href="/stores/<%= @store.id %>/station_datas";
tishi_alert("新建成功!");
<% end %>

app/views/station_datas/destroy.js.erb
<% if @status == 0 %>
tishi_alert("删除失败!");
window.location.reload();
<% else %>
tishi_alert("删除成功!");
window.location.href="/stores/<%= @store.id %>/station_datas";
<% end %>

app/views/station_datas/edit.js.erb
$("#station_div").html("<%= j(render :partial => "edit") %>");
popup("#station_div");

app/views/station_datas/index.html.erb
<div class="main">
  <div class="box">
    <div class="data_box">
      <div class="data_menu">
        <% if permission?(:base_datas, :new_station_data) %><%= link_to "新建工位", new_store_station_data_path(@store), remote: :true, "data-type" => 'script', :class =>"add_btn" %><% end %></div>
      <div class="clear"></div>
      <div class="data_body">
        <div class="station-data">
          <table width="100%" border="0" cellspacing="0" cellpadding="0" class="data_table">
            <thead>
              <tr class="hbg">
                <th>工位编号</th>
                <th>名称</th>
                <th>可施工服务</th>
                <th>工位状态</th>
                <th>是否有工控机</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <% @stations.each do |station| %>
                <tr>
                  <td width =150"><%= station.code %></td>
                  <td width =180"><%= station.name %></td>
                  <td width =200"><%= station.products.where(["status = ?", Product::IS_VALIDATE[:YES]]).map(&:name).join("、") %></td>
                  <td width =150"><%= Station::STAT_NAME[station.status] %></td>
                  <td width =100"><%= station.is_has_controller ? "有" : "无" %></td>
                  <td><% if permission?(:base_datas, :edit_station_data) %><%= link_to "编辑", edit_store_station_data_path(@store, station), remote: :true, "data-type" => 'script' %><% end %>
                      <% if permission?(:base_datas, :del_station_data) %><%= link_to "删除", "/stores/#{@store.id}/station_datas/#{station.id}",remote: :true, "data-type" => 'script',  :confirm => "确定需要删除工位吗？", :method => 'delete' %><% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @stations, :class => "pageTurn", :previous_label => "上一页",
            :next_label => "下一页"  unless @stations.empty?%>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="mask"></div>
<div class="tab_popup" id="station_div" style="display:none;">
</div>

app/views/station_datas/new.js.erb
$("#station_div").html("<%= j(render :partial => "new") %>");
popup("#station_div");

app/views/station_datas/update.js.erb
<% if @status==2 %>
tishi_alert("编辑失败，已有同编号的工控机!");
<% elsif @status==0 %>
tishi_alert("编辑失败!");
<% else %>
window.location.reload();
tishi_alert("编辑成功!");
<% end %>